services:
  web:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8080:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
